DATASET:
  NAME: "BLCA"
  NUM_CLASSES: 2
  CLASS_NAMES: [ "High Grade", "Low Grade" ]
  SPARSITY_RATES: 0.6

ENCODER:
  HID_DIMS: 256
  DROPOUT_RATE: 0.2

ATTENTION:
  NUM_HEADS: 8

DECODER:
  HID_DIMS: 256
  NUM_LAYERS: 2
  DROPOUT_RATE: 0.2
  NEGATIVE_SLOPE: 0.2

SOLVER:
  LR: 0.00017
  WD: 0.001

COMET:
  PROJECT_NAME: "magnet_blca"

TUNE:
  METRIC: "val_auprc"